graceperiod: 30
use-ranks: false
deathchests:
  enabled: true
  deathchest-min-items: 5
  enabled-worlds:
    - 'world'
scoreboard:
  enabled: true
  title: '&b&l%player_world%'
  lines:
    - '&8&m                        '
    - '&7» &3Warcoins: &c%warcoins%'
    - '&7» &3Money: &f%vault_eco_balance_fixed% ⛁'
    - '&7» &3Claim Blocks: &f%griefprevention_remainingclaims%'
    - '&r'
    - '&7» &3Kills: &f%statistic_player_kills%'
    - '&7» &3Deaths: &f%statistic_deaths%'
    - '&7» &3Power: &f%mcmmo_power_level%'
    - '&c'
    - '&7» &3Voteparty: &f%VotingPlugin_VotePartyVotesCurrent%&7/&f%VotingPlugin_VotePartyVotesRequired%'
    - '&8&m                        &r'
    - '&7play.&3furnesse&7.com'
announcer:
  enabled: true
  delay: 420
  "1":
    - "an announce"
chat:
  enabled: true
  formats:
    default: 
      format: '&8[&f%player_world%&8] %core_rank_prefix% &7%player_name% &8» &f%msg%'
      click-command: '/msg %player_name%'
      tooltip:
        - 'haiosudf'
        - 'asdfhbgfd'
        - 'sgdsfbvds'
        - 'fgbgfdsgb'
database:
  enabled: false
  mysql:
    host: 'localhost'
    port: 3306
    database: 'fcore'
    username: 'root'
    password: 'password'
disable-recipes:
  - 'HOPPER'
  