graceperiod: 30
use_ranks: false
deathchests:
  enabled: false
  spawn_chest_on_highest_block: true
  deathchest_inv_title: "&c%player%'s &8Deathchest"
  void_spawning: true
  auto_equip_armor: true
  spawn_in_lava: true
  drop_items_after_expire: false
  expire_time: -1
  disabled_worlds:
  - 'warzone'
  - 'spawn_world'
  gui:
    prev_item:
      material: STONE_BUTTON
      amount: 1
      displayname: "&a<----"
      lore:
      - "&7Return to previous page"
    next_item:
      material: STONE_BUTTON
      amount: 1
      displayname: "&a---->"
      lore:
      - "&7Continue to next page"
    deathchest_item:
      material: PLAYER_HEAD
      amount: 1
      displayname: "&c%player%"
      lore:
      - "&7World: &a%world%"
      - "&7X&a%xloc% &7Y&a%yloc% &7Z&a%zloc%"
scoreboard:
  enabled: false
  title: '&b&l%player_world%'
  sidebar_updatetime: 10
  lines:
    - '&8&m                        '
    - '&7» &3Warcoins: &c%warcoins%'
    - '&7» &3Money: &f%vault_eco_balance_fixed% ⛁'
    - '&7» &3Claim Blocks: &f%griefprevention_remainingclaims%'
    - '&r'
    - '&7» &3Kills: &f%statistic_player_kills%'
    - '&7» &3Deaths: &f%statistic_deaths%'
    - '&7» &3Power: &f%mcmmo_power_level%'
    - '&c'
    - '&7» &3Voteparty: &f%VotingPlugin_VotePartyVotesCurrent%&7/&f%VotingPlugin_VotePartyVotesRequired%'
    - '&8&m                        &r'
    - '&7play.&3furnesse&7.com'
announcer:
  enabled: true
  delay: 420
  "1":
    - "an announce"
chat:
  enabled: true
  formats:
    default:
      format: '&8[&f%player_world%&8] %core_rank_prefix% &7%player_name% &8» &f%msg%'
      click-command: '/msg %player_name%'
      tooltip:
        - 'haiosudf'
        - 'asdfhbgfd'
database:
  enabled: false
  mysql:
    host: 'localhost'
    port: 3306
    database: 'fcore'
    username: 'root'
    password: 'password'
disable-recipes:
  - 'HOPPER'
