main: com.Furnesse.core.Core
author: 6u5t4v
version: 1.0
name: Core
api-version: 1.14
website: www.furnesse.com
depend: [Vault, PlaceholderAPI]
commands:
  rank:
    description: Rank managing
    permissions:
      core.rank.*:
  core:
    description: Main command to view all Core's commands
    permissions:
      core.*:
  items:
    description: custom items.
    permission: core.items
  jellylegs:
    description: Reduces the falldamage for the player
    permission: core.jellylegs
  nightvision:
    aliases: 
    - nv
    - nightv
    - nvision
    description: Gives the player nightvision forever
    permission: core.nightvision
permissions:
  core.reload:
    default: false
    description: allow /reload
  core.*:
    description: Wildcard permissions.
    default: false
    children:
      core.jellylegs: true
      core.rank.*: true
      core.nightvision: true
      core.deathchests.*: true
      core.reload: true
      core.items.*: true
      core.help: true
      core.reload: true
      core.sb.toggle: true
      core.dc.clear: true
      core.dc.load: true
  core.sb.toggle:
    description: toggle on/off your scoreboard
    default: true
  core.dc.clear:
    description: Clear all active deathchests
    default: false
  core.dc.load:
    description: reload all deathchests from storage
    default: false
  core.items.*:
    description: wildcard for custom items
    default: false
    children:
      core.items.give: true
      core.items.list: true
      core.items.menu: true
  core.items.give:
    description: give players custom items
    default: false
  core.items.list:
    description: view a list of all available custom items
    default: false
  core.items.menu:
    description: open the custom items menu
    default: false
  core.deathchests.*:
    description: wildcard for deathchests.
    default: false
    children:
      core.deathchests.clear: true
  core.deathchests.clear:
    description: remove all active deathchests.
    default: false
  core.rank.*:
    description: Wildcard for rank permissions.
    default: false
    children:
      core.rank.ranks: true
      core.rank.create: true
      core.rank.user: true
      core.rank.remove: true
      core.rank.modify: true
      core.rank.delete: true
  core.rank.list:
    description: View all ranks.
    default: true
  core.rank.create:
    description: Create a new rank.
    default: false
  core.rank.player:
    description: set,remove,modify player's rank.
    default: false
  core.rank.remove:
    description: Remove a rank entirely.
    default: false
  core.rank.modify:
    description: set prefix,suffix and add/remove permissions from a rank.
    default: false
  core.nightvision:
    description: Allow player to turn on nightvision.
    default: false
  core.jellylegs:
    description: Allow player to have a reduced falldamage.
    default: false
  