main: com.Furnesse.core.Core
author: 6u5t4v
version: 1.5.32
name: Core
api-version: 1.15
website: www.furnesse.com
depend: [Vault, PlaceholderAPI]
softdepend: [HeadDatabase]
commands:
  fcdeathchest:
    description: Deathchests managing
    aliases:
    - fcdc
    - fcdchest
  fcranks:
    description: Rank managing
  fcore:
    description: Main command to view all Core's commands
    aliases:
    - fc
  fcitems:
    description: custom items.
    aliases:
    - fci
permissions:
  core.deathcoords:
    description: get coords for where you died.
  core.*:
    description: Wildcard permissions.
    default: false
    children:
      core.sb.*: true
      core.dc.*: true
      core.rank.*: true
      core.items.*: true
      core.reload: true
      core.help: true      
  core.sb.*:
    description: toggle on/off your scoreboard
    default: false
    children:
      core.sb.toggle: true
      core.sb.reload: true
  core.dc.*:
    description: Clear all active deathchests
    default: false
    children:
      core.dc.reload: true
      core.dc.clear: true
      core.dc.menu: true
  core.items.*:
    description: wildcard for custom items
    default: false
    children:
      core.items.give: true
      core.items.list: true
      core.items.menu: true
  core.ranks.*:
    description: Wildcard for rank permissions.
    default: false
    children:
      core.ranks.list: true
      core.ranks.create: true
      core.ranks.modifyuser.*: true
      core.ranks.modifyrank.*: true
      core.ranks.delete: true
  core.ranks.modifyuser.*:
    description: set/remove rank for a user while also modifying his personal prefix and suffix
    default: false
    children:
      core.ranks.modifyuser.setrank: true
      core.ranks.modifyuser.removerank: true
      core.ranks.modifyuser.addperm: true
      core.ranks.modifyuser.removeperm: true
      core.ranks.modifyuser.setprefix: true
      core.ranks.modifyuser.setsuffix: true
  core.ranks.modifyrank.*:
    description: modify ranks
    default: false
    children:
      core.ranks.modifyrank.setprefix: true
      core.ranks.modifyrank.setsuffix: true
      core.ranks.modifyrank.addperm: true
      core.ranks.modifyrank.removeperm: true
      core.ranks.modifyrank.addinheritsrank: true